### ISSUE TITLE
Support pipelining

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretStore#19] opened 2020-09-18 23:24 UTC
For example:

```pwsh
Get-Secret -Name foo -Vault OtherVault  | Set-Secret -Vault SecretStore
```

Should be just a matter of adding the pipeline options to the parameter attribute.

**Comment by PaulHigin** [comment] 2020-09-19 22:58
Good point.  I agree this should be supported.

**Comment by SydneyhSmith** [comment] 2020-09-23 15:19
Closing this as a duplicate of https://github.com/PowerShell/SecretManagement/issues/36

**Closed** 2020-09-23 15:19 UTC
