### ISSUE TITLE
Set-SecretStorePassword unintuitive for inputs

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/SecretStore#33] opened 2020-10-09 18:00 UTC
I wanted to use `Set-SecretStorePassword` and tried first with a positional parameter:

```
> Set-SecretStorePassword banana
Set-SecretStorePassword: A positional parameter cannot be found that accepts argument 'banana'.
```

So then I looked for the right parameter. Maybe it wants a SecureString?

```
> Set-SecretStorePassword -<tab>
Verbose              WarningAction        WarningVariable      OutBuffer
Debug                InformationAction    InformationVariable  PipelineVariable
ErrorAction          ErrorVariable        OutVariable
```

Hmmm, ok maybe it'll prompt me for the right parameter if I just execute it with no arguments?

```
> Set-SecretStorePassword
Old password
Enter password:
```

Oh! Hmmm, what is this? Oh it's literally prompting me the old fashioned way!

How do I automate this or get it to interact with other PowerShell stuff?

**Comment by SydneyhSmith** [comment] 2020-10-12 21:40
Thanks @rjmholt we made this choice to be safest...curious for more use cases in terms of why you may want to update the secret store password (rather than secrets in the secret store) during automation, would love to better understand this scenario...
@adityapatwardhan @TravisEz13 do you have any thought?

**Comment by rjmholt** [comment] 2020-10-12 22:39
For me I think it's as much about UX and the expectation set by both PowerShell's general conventions and the verb used. The cmdlet is essentially interactive-only (which is already quite unusual for PowerShell), but also despite using the `Set-` verb (which implies to me that it will take in a value to use), it actually *reads* from the host for a new password.

I can imagine this being an issue in terms of user expectations and needing to learn the idiosyncrasies of this cmdlet, but also it could have issues in other hosts.

But generally for me, I think:

- PowerShell is intended to be composable and automatable, and this doesn't play into that
- While I don't really know if there's a non-interactive scenario for secret store passwords, the limits of our imagination have been surpassed by real world use. Much of PowerShell is intended to actually abstract away interactive vs automation scenarios
- Reading from the host directly being safer implies some weakness in the alternative method of passing in a securestring/credential, and I'm not entirely convinced that's the case, but also we should discuss it if we think it is

**Comment by ThomasNieto** [comment] 2020-10-12 23:01
I believe this is a dup of #26 to add `-Password` and `-NewPassword` parameters.

**Comment by PaulHigin** [comment] 2020-10-29 23:36
I am closing this as a duplicate of #26

**Closed by PaulHigin** 2020-10-29 23:36 UTC
Labels: question
